name: get contributions

on:
  schedule:
    - cron: "0 12 * * *" 
  workflow_dispatch:

jobs:
  get-contributions:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: gh-contribs
    steps:
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install reqs
      run: python -m pip install requests
    - uses: actions/checkout@v2
    - name: get-contribs
      shell: bash
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: python gh-contribs/get.py
    - name: add and commit	
      run: |-	
        git add .	
        git config user.name "Automated"	
        git config user.email "actions@users.noreply.github.com"	
        git commit -m "Latest data" 	
    - name: push	
      run: git push